# emot python library: https://github.com/NeelShah18/emot
# Taken and adapted from:
# https://github.com/NeelShah18/emot/blob/master/emot/emo_unicode.py
# -*- coding: UTF-8 -*-


"""
Emoticons and Emoji data dictonary
"""


__all__ = ['EMOTICONS', ]

EMOTICONS = {
    u":-\)":"<smile>",
    u":\)":"<smile>",
    u":-\]":"<smile>",
    u":\]":"<smile>",
    u":-3":"<smile>",
    u":3":"<smile>",
    u":->":"<smile>",
    u":>":"<smile>",
    u"8-\)":"<smile>",
    u":o\)":"<smile>",
    u":-\}":"<smile>",
    u":\}":"<smile>",
    u":c\)":"<smile>",
    u":\^\)":"<smile>",
    u"=\]":"<smile>",
    u"=\)":"<smile>",
    u":-D":"<smile>",
    u":D":"<smile>",
    u"8-D":"<smile>",
    u"8D":"<smile>",
    u"X-D":"<smile>",
    u"XD":"<smile>",
    u"=D":"<smile>",
    u"=3":"<smile>",
    u"B\^D":"<smile>",
    u":-\)\)":"<smile>",
    u":-\(":"<sadface>",
    u":\(":"<sadface>",
    u":-c":"<sadface>",
    u":c":"<sadface>",
    u":-<":"<sadface>",
    u":<":"<sadface>",
    u":-\[":"<sadface>",
    u":\[":"<sadface>",
    u":-\|\|":"<sadface>",
    u">:\[":"Sad",
    u":\{":"Sad",
    u":@":"Sad",
    u">:\(":"Sad",
    u":'-\(":"Sad",
    u":'\(":"Sad",
    u":'-\)":"<smile>",
    u":'\)":"<smile>",
    u"D-':":"Horror",
    u"D:<":"Disgust",
    u"D:":"Sadness",
    u"D8":"Dismay",
    u"D;":"Dismay",
    u"D=":"Dismay",
    u"DX":"Dismay",
    u":-O":"<smile>",
    u":O":"<smile>",
    u":-o":"<smile>",
    u":o":"<smile>",
    u":-0":"<smile>",
    u"8-0":"<smile>",
    u">:O":"<smile>",
    u":-\*":"<smile>",
    u":\*":"<smile>",
    u":X":"<smile>",
    u";-\)":"<smile>",
    u";\)":"<smile>",
    u"\*-\)":"<smile>",
    u"\*\)":"<smile>",
    u";-\]":"<smile>",
    u";\]":"<smile>",
    u";\^\)":"<smile>",
    u":-,":"<smile>",
    u";D":"<smile>",
    u":-P":"<lolface>",
    u":P":"<lolface>",
    u"X-P":"<lolface>",
    u"XP":"<lolface>",
    u":-Þ":"<lolface>",
    u":Þ":"<lolface>",
    u":b":"<lolface>",
    u"d:":"<lolface>",
    u"=p":"<lolface>",
    u">:P":"<lolface>",
    u":-/":"Annoyed",
    u":/":"Annoyed",
    u":-\.":"Annoyed",
    u">:/":"Annoyed",
    u"=/":"Annoyed",
    u":L":"Annoyed",
    u"=L":"Annoyed",
    u":S":"Annoyed",
    u":-\|":"Neutral",
    u":\|":"Neutral",
    u":$":"Embarrassed",
    u":-x":"Sealed lips",
    u":x":"Sealed lips",
    u":-#":"Sealed lips",
    u":#":"Sealed lips",
    u":-&":"Sealed lips",
    u":&":"Sealed lips",
    u"O:-\)":"<smile>",
    u"O:\)":"<smile>",
    u"0:-3":"<smile>",
    u"0:3":"<smile>",
    u"0:-\)":"<smile>",
    u"0:\)":"<smile>",
    u":-b":"<lolface>",
    u"0;\^\)":"Innocent",
    u"<:-\|":"Dump",
    u"\(>_<\)":"Troubled",
    u"\(>_<\)>":"Troubled",
    u"\(';'\)":"Baby",
    u"\(\^\^>``":"Nervous",
    u"\(\^_\^;\)":"Nervous",
    u"\(-_-;\)":"Nervous",
    u"\(~_~;\) \(・\.・;\)":"Nervous",
    u"\(\^_-\)":"<smile>",
    u"\(\(\+_\+\)\)":"Confused",
    u"\(\+o\+\)":"Confused",
    u"\(o\|o\)":"Ultraman",
    u"\^_\^":"<smile>",
    u"\(\^_\^\)/":"<smile>",
    u"\(\^O\^\)／":"<smile>",
    u"\(\^o\^\)／":"<smile>",
    u"\('_'\)":"Sad",
    u"\(/_;\)":"Sad",
    u"\(T_T\) \(;_;\)":"Sad",
    u"\(;_;":"Sad",
    u"\(;_:\)":"Sad",
    u"\(;O;\)":"Sad",
    u"\(:_;\)":"Sad",
    u"\(ToT\)":"Sad",
    u";_;":"Sad",
    u";-;":"Sad",
    u";n;":"Sad",
    u";;":"Sad",
    u"Q\.Q":"Sad",
    u"T\.T":"Sad",
    u"QQ":"Sad",
    u"Q_Q":"Sad",
    u"\(-\.-\)":"Shame",
    u"\(-_-\)":"Shame",
    u"\(一一\)":"Shame",
    u"\(；一_一\)":"Shame",
    u"\(=_=\)":"Tired",
    u"\(\.\.\)":"Sad",
    u"\(\._\.\)":"Sad",
    u"\(?_?\)":"Confusion",
    u">\^_\^<":"<smile>",
    u"<\^!\^>":"<smile>",
    u"\^/\^":"<smile>",
    u"\（\*\^_\^\*）" :"<smile>",
    u"\(\^<\^\) \(\^\.\^\)":"<smile>",
    u"\(^\^\)":"<smile>",
    u"\(\^\.\^\)":"<smile>",
    u"\(\^_\^\.\)":"<smile>",
    u"\(\^_\^\)":"<smile>",
    u"\(\^\^\)":"<smile>",
    u"\(\^J\^\)":"<smile>",
    u"\(\*\^\.\^\*\)":"<smile>",
    u"\(\^—\^\）":"<smile>",
    u"\(#\^\.\^#\)":"<smile>",
    u"\(\*\^0\^\*\)":"<smile>",
    u"\(\*_\*\)":"<smile>",
    u"\(\*_\*;":"<smile>",
    u"\(\+_\+\) \(@_@\)":"<smile>",
    u"\(\*\^\^\)v":"<smile>",
    u"\(\^_\^\)v":"<smile>",
    u'\(-"-\)':"Worried",
    u"\(ーー;\)":"Worried",
    u"\(\＾ｖ\＾\)":"<smile>",
    u"\(\＾ｕ\＾\)":"<smile>",
    u"\(\^\)o\(\^\)":"<smile>",
    u"\(\^O\^\)":"<smile>",
    u"\(\^o\^\)":"<smile>",
    u"\)\^o\^\(":"<smile>",
    u":O o_O":"<smile>",
    u"o_0":"<smile>",
    u"o\.O":"<smile>",
    u"\(o\.o\)":"<smile>",
    u"oO":"<smile>",
    u"\(\*￣m￣\)":"Dissatisfied",
    u"x3":"<smile>",
    u"xxx":"<smile>",
    u"xx":"<smile>",
    u"c:":"<smile>",
    u":d":"<lolface>",
    u"<3":"Heart",
    u"</3":"Broken heart",
    u"- ___ -":"Sad",
    u":\|\|":"Sad",
    u":l": "Sad",
    u":p": "<lolface>",
    u"xp": "<lolface>",
    u";p": "<lolface>",


}
