#TODO: add reference
#TODO: I'm afraid these will add more frequency to certain words
#like laughing, big grin or laugh with glasses. (laugh x 2 after lemmatization)
# -*- coding: UTF-8 -*-


"""
Emoticons and Emoji data dictonary
"""


__all__ = ['EMOTICONS', ]

EMOTICONS = {
    u":-\)":"Happy",
    u":\)":"Happy",
    u":-\]":"Happy",
    u":\]":"Happy",
    u":-3":"Happy",
    u":3":"Happy",
    u":->":"Happy",
    u":>":"Happy",
    u"8-\)":"Happy",
    u":o\)":"Happy",
    u":-\}":"Happy",
    u":\}":"Happy",
    u":c\)":"Happy",
    u":\^\)":"Happy",
    u"=\]":"Happy",
    u"=\)":"Happy",
    u":-D":"Happy",
    u":D":"Happy",
    u"8-D":"Happy",
    u"8D":"Happy",
    u"X-D":"Happy",
    u"XD":"Happy",
    u"=D":"Happy",
    u"=3":"Happy",
    u"B\^D":"Happy",
    u":-\)\)":"Happy",
    u":-\(":"Sad",
    u":\(":"Sad",
    u":-c":"Sad",
    u":c":"Sad",
    u":-<":"Sad",
    u":<":"Sad",
    u":-\[":"Sad",
    u":\[":"Sad",
    u":-\|\|":"Sad",
    u">:\[":"Sad",
    u":\{":"Sad",
    u":@":"Sad",
    u">:\(":"Sad",
    u":'-\(":"Sad",
    u":'\(":"Sad",
    u":'-\)":"Happy",
    u":'\)":"Happy",
    u"D-':":"Horror",
    u"D:<":"Disgust",
    u"D:":"Sadness",
    u"D8":"Dismay",
    u"D;":"Dismay",
    u"D=":"Dismay",
    u"DX":"Dismay",
    u":-O":"Surprise",
    u":O":"Surprise",
    u":-o":"Surprise",
    u":o":"Surprise",
    u":-0":"Shock",
    u"8-0":"Yawn",
    u">:O":"Yawn",
    u":-\*":"Kiss",
    u":\*":"Kiss",
    u":X":"Kiss",
    u";-\)":"Wink",
    u";\)":"Wink",
    u"\*-\)":"Wink",
    u"\*\)":"Wink",
    u";-\]":"Wink",
    u";\]":"Wink",
    u";\^\)":"Wink",
    u":-,":"Wink",
    u";D":"Wink",
    u":-P":"Happy",
    u":P":"Happy",
    u"X-P":"Happy",
    u"XP":"Happy",
    u":-Þ":"Happy",
    u":Þ":"Happy",
    u":b":"Happy",
    u"d:":"Happy",
    u"=p":"Happy",
    u">:P":"Happy",
    u":-/":"Annoyed",
    u":/":"Annoyed",
    u":-\.":"Annoyed",
    u">:/":"Annoyed",
    u"=/":"Annoyed",
    u":L":"Annoyed",
    u"=L":"Annoyed",
    u":S":"Annoyed",
    u":-\|":"Neutral",
    u":\|":"Neutral",
    u":$":"Embarrassed",
    u":-x":"Sealed lips",
    u":x":"Sealed lips",
    u":-#":"Sealed lips",
    u":#":"Sealed lips",
    u":-&":"Sealed lips",
    u":&":"Sealed lips",
    u"O:-\)":"Innocent",
    u"O:\)":"Innocent",
    u"0:-3":"Innocent",
    u"0:3":"Innocent",
    u"0:-\)":"Innocent",
    u"0:\)":"Innocent",
    u":-b":"Happy",
    u"0;\^\)":"Innocent",
    u">:-\)":"Evil",
    u">:\)":"Evil",
    u"\}:-\)":"Evil",
    u"\}:\)":"Evil",
    u"3:-\)":"Evil",
    u"3:\)":"Evil",
    u">;\)":"Evil",
    u"\|;-\)":"Cool",
    u"\|-O":"Bored",
    u"#-\)":"Party",
    u"%-\)":"Confused",
    u"%\)":"Confused",
    u":-###..":"Sick",
    u":###..":"Sick",
    u"<:-\|":"Dump",
    u"\(>_<\)":"Troubled",
    u"\(>_<\)>":"Troubled",
    u"\(';'\)":"Baby",
    u"\(\^\^>``":"Nervous",
    u"\(\^_\^;\)":"Nervous",
    u"\(-_-;\)":"Nervous",
    u"\(~_~;\) \(・\.・;\)":"Nervous",
    u"\(-_-\)zzz":"Sleeping",
    u"\(\^_-\)":"Wink",
    u"\(\(\+_\+\)\)":"Confused",
    u"\(\+o\+\)":"Confused",
    u"\(o\|o\)":"Ultraman",
    u"\^_\^":"Joyful",
    u"\(\^_\^\)/":"Joyful",
    u"\(\^O\^\)／":"Joyful",
    u"\(\^o\^\)／":"Joyful",
    u"\(__\)":"Respect",
    u"_\(\._\.\)_":"Respect",
    u"<\(_ _\)>":"Respect",
    u"<m\(__\)m>":"Respect",
    u"m\(__\)m":"Respect",
    u"m\(_ _\)m":"Respect",
    u"\('_'\)":"Sad",
    u"\(/_;\)":"Sad",
    u"\(T_T\) \(;_;\)":"Sad",
    u"\(;_;":"Sad",
    u"\(;_:\)":"Sad",
    u"\(;O;\)":"Sad",
    u"\(:_;\)":"Sad",
    u"\(ToT\)":"Sad",
    u";_;":"Sad",
    u";-;":"Sad",
    u";n;":"Sad",
    u";;":"Sad",
    u"Q\.Q":"Sad",
    u"T\.T":"Sad",
    u"QQ":"Sad",
    u"Q_Q":"Sad",
    u"\(-\.-\)":"Shame",
    u"\(-_-\)":"Shame",
    u"\(一一\)":"Shame",
    u"\(；一_一\)":"Shame",
    u"\(=_=\)":"Tired",
    u"\(=\^\·\^=\)":"cat",
    u"\(=\^\·\·\^=\)":"cat",
    u"=_\^=	":"cat",
    u"\(\.\.\)":"Sad",
    u"\(\._\.\)":"Sad",
    u"\(?_?\)":"Confusion",
    u">\^_\^<":"Laugh",
    u"<\^!\^>":"Laugh",
    u"\^/\^":"Laugh",
    u"\（\*\^_\^\*）" :"Laugh",
    u"\(\^<\^\) \(\^\.\^\)":"Laugh",
    u"\(^\^\)":"Laugh",
    u"\(\^\.\^\)":"Laugh",
    u"\(\^_\^\.\)":"Laugh",
    u"\(\^_\^\)":"Laugh",
    u"\(\^\^\)":"Laugh",
    u"\(\^J\^\)":"Laugh",
    u"\(\*\^\.\^\*\)":"Laugh",
    u"\(\^—\^\）":"Laugh",
    u"\(#\^\.\^#\)":"Laugh",
    u"\（\^—\^\）":"Waving",
    u"\(;_;\)/~~~":"Waving",
    u"\(\^\.\^\)/~~~":"Waving",
    u"\(-_-\)/~~~ \($\·\·\)/~~~":"Waving",
    u"\(T_T\)/~~~":"Waving",
    u"\(ToT\)/~~~":"Waving",
    u"\(\*\^0\^\*\)":"Excited",
    u"\(\*_\*\)":"Amazed",
    u"\(\*_\*;":"Amazed",
    u"\(\+_\+\) \(@_@\)":"Amazed",
    u"\(\*\^\^\)v":"Laugh",
    u"\(\^_\^\)v":"Laugh",
    u"\(\(d[-_-]b\)\)":"Headphones",
    u'\(-"-\)':"Worried",
    u"\(ーー;\)":"Worried",
    u"\(\^0_0\^\)":"Eyeglasses",
    u"\(\＾ｖ\＾\)":"Happy",
    u"\(\＾ｕ\＾\)":"Happy",
    u"\(\^\)o\(\^\)":"Happy",
    u"\(\^O\^\)":"Happy",
    u"\(\^o\^\)":"Happy",
    u"\)\^o\^\(":"Happy",
    u":O o_O":"Surprised",
    u"o_0":"Surprised",
    u"o\.O":"Surpised",
    u"\(o\.o\)":"Surprised",
    u"oO":"Surprised",
    u"\(\*￣m￣\)":"Dissatisfied",
    u"x3":"Happy",
    u"xxx":"Kiss",
    u"xx":"Kiss",
    u"c:":"Happy",
    u":d":"Happy",
    u"<3":"Love",
    u"</3":"Sad",
    u"- ___ -":"Sad",
    u":\|\|":"Sad",
    u":l": "Sad",
    u":p": "Happy",
    u"xp": "Happy",
    u";p": "Happy",


}